slam_toolbox:
  ros__parameters:

    # Plugin params
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    # ROS frame & topic setup
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    mode: mapping  # or localization

    # Map size & resolution
    resolution: 0.02                 # grid size 2 cm for smoother map
    map_update_interval: 10.0       # update map every 10 s

    # Laser range limits (match RPLidar specs)
    minimum_laser_range: 0.2         # drop readings < 0.2 m
    maximum_laser_range: 12.0        # drop readings > 12 m

    # Scan handling
    throttle_scans: 2                # process every 2nd scan
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0

    # Motion thresholds for map updates
    minimum_travel_distance: 0.5     # only update when moved ≥ 0.5 m
    minimum_travel_heading: 0.3      # only update when rotated ≥ 0.3 rad

    # TF & timing
    transform_publish_period: 0.05   # publish odom at 20 Hz
    transform_timeout: 0.2
    transform_tolerance: 0.1
    tf_buffer_duration: 60.0         # keep TF up to 60 s

    # Message filter queue to avoid dropping scans
    message_filter_queue_size: 50

    # Loop closure & matching
    use_scan_matching: true
    use_scan_barycenter: true
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0

    # Correlation search parameters
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # Loop closure search parameters
    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan matcher penalties & offsets
    distance_variance_penalty: 0.5
    angle_variance_penalty: 1.0
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true

    # Miscellaneous
    debug_logging: false
    minimum_time_interval: 0.5
    stack_size_to_use: 40000000
    enable_interactive_mode: true
